version: '3'
services:
  spring-app:
    build: .
    ports:
      - "9925:9924"
    links:
      - redis
    networks:
      - my-network
    depends_on:
      - redis
    environment:
      - "SPRING_PROFILES_ACTIVE=cron"
  spring-app-without-cron:
    build: .
    ports:
      - "8085-8090:9924"
    links:
      - redis
    networks:
      - my-network
    depends_on:
      - redis
  redis:
    image: redis
    ports:
      - "6378:6379"
    networks:
      - my-network
networks:
  my-network:
    driver: bridge